export interface ThemeColors {
  name: string;
  id: string;
  navBg: string;
  navText: string;
  navHover: string;
  heroGradient: string;
  accent: string;
  accentLight: string;
  accentDark: string;
  sectionAlt: string;
  cardBg: string;
  cardBorder: string;
  footerBg: string;
  footerText: string;
  buttonPrimary: string;
  buttonHover: string;
  tag: string;
  preview: string;
}

export const themes: ThemeColors[] = [
  {
    name: "Tostem Classic",
    id: "tostem-classic",
    navBg: "bg-gray-900",
    navText: "text-white",
    navHover: "hover:text-amber-400",
    heroGradient: "from-gray-900 via-gray-800 to-gray-900",
    accent: "bg-amber-500",
    accentLight: "bg-amber-100 text-amber-800",
    accentDark: "bg-amber-700",
    sectionAlt: "bg-gray-50",
    cardBg: "bg-white",
    cardBorder: "border-gray-200",
    footerBg: "bg-gray-900",
    footerText: "text-gray-300",
    buttonPrimary: "bg-amber-500 hover:bg-amber-600 text-white",
    buttonHover: "hover:bg-amber-600",
    tag: "bg-amber-500",
    preview: "#f59e0b",
  },
  {
    name: "Midnight Sapphire",
    id: "midnight-sapphire",
    navBg: "bg-slate-900",
    navText: "text-white",
    navHover: "hover:text-cyan-400",
    heroGradient: "from-slate-900 via-slate-800 to-indigo-950",
    accent: "bg-cyan-500",
    accentLight: "bg-cyan-100 text-cyan-800",
    accentDark: "bg-cyan-700",
    sectionAlt: "bg-slate-50",
    cardBg: "bg-white",
    cardBorder: "border-slate-200",
    footerBg: "bg-slate-900",
    footerText: "text-slate-300",
    buttonPrimary: "bg-cyan-500 hover:bg-cyan-600 text-white",
    buttonHover: "hover:bg-cyan-600",
    tag: "bg-cyan-500",
    preview: "#06b6d4",
  },
  {
    name: "Emerald Luxe",
    id: "emerald-luxe",
    navBg: "bg-emerald-950",
    navText: "text-white",
    navHover: "hover:text-emerald-300",
    heroGradient: "from-emerald-950 via-emerald-900 to-teal-950",
    accent: "bg-emerald-500",
    accentLight: "bg-emerald-100 text-emerald-800",
    accentDark: "bg-emerald-700",
    sectionAlt: "bg-emerald-50",
    cardBg: "bg-white",
    cardBorder: "border-emerald-200",
    footerBg: "bg-emerald-950",
    footerText: "text-emerald-200",
    buttonPrimary: "bg-emerald-500 hover:bg-emerald-600 text-white",
    buttonHover: "hover:bg-emerald-600",
    tag: "bg-emerald-500",
    preview: "#10b981",
  },
  {
    name: "Royal Burgundy",
    id: "royal-burgundy",
    navBg: "bg-rose-950",
    navText: "text-white",
    navHover: "hover:text-rose-300",
    heroGradient: "from-rose-950 via-rose-900 to-pink-950",
    accent: "bg-rose-500",
    accentLight: "bg-rose-100 text-rose-800",
    accentDark: "bg-rose-700",
    sectionAlt: "bg-rose-50",
    cardBg: "bg-white",
    cardBorder: "border-rose-200",
    footerBg: "bg-rose-950",
    footerText: "text-rose-200",
    buttonPrimary: "bg-rose-500 hover:bg-rose-600 text-white",
    buttonHover: "hover:bg-rose-600",
    tag: "bg-rose-500",
    preview: "#f43f5e",
  },
  {
    name: "Obsidian Gold",
    id: "obsidian-gold",
    navBg: "bg-neutral-950",
    navText: "text-amber-100",
    navHover: "hover:text-yellow-400",
    heroGradient: "from-neutral-950 via-neutral-900 to-yellow-950",
    accent: "bg-yellow-500",
    accentLight: "bg-yellow-100 text-yellow-800",
    accentDark: "bg-yellow-600",
    sectionAlt: "bg-neutral-100",
    cardBg: "bg-white",
    cardBorder: "border-yellow-200",
    footerBg: "bg-neutral-950",
    footerText: "text-yellow-100",
    buttonPrimary: "bg-yellow-500 hover:bg-yellow-600 text-black",
    buttonHover: "hover:bg-yellow-600",
    tag: "bg-yellow-500",
    preview: "#eab308",
  },
  {
    name: "Arctic Frost",
    id: "arctic-frost",
    navBg: "bg-sky-950",
    navText: "text-white",
    navHover: "hover:text-sky-300",
    heroGradient: "from-sky-950 via-sky-900 to-blue-950",
    accent: "bg-sky-500",
    accentLight: "bg-sky-100 text-sky-800",
    accentDark: "bg-sky-700",
    sectionAlt: "bg-sky-50",
    cardBg: "bg-white",
    cardBorder: "border-sky-200",
    footerBg: "bg-sky-950",
    footerText: "text-sky-200",
    buttonPrimary: "bg-sky-500 hover:bg-sky-600 text-white",
    buttonHover: "hover:bg-sky-600",
    tag: "bg-sky-500",
    preview: "#0ea5e9",
  },
  {
    name: "Volcanic Ember",
    id: "volcanic-ember",
    navBg: "bg-stone-900",
    navText: "text-orange-100",
    navHover: "hover:text-orange-400",
    heroGradient: "from-stone-900 via-stone-800 to-orange-950",
    accent: "bg-orange-500",
    accentLight: "bg-orange-100 text-orange-800",
    accentDark: "bg-orange-700",
    sectionAlt: "bg-stone-100",
    cardBg: "bg-white",
    cardBorder: "border-orange-200",
    footerBg: "bg-stone-900",
    footerText: "text-orange-200",
    buttonPrimary: "bg-orange-500 hover:bg-orange-600 text-white",
    buttonHover: "hover:bg-orange-600",
    tag: "bg-orange-500",
    preview: "#f97316",
  },
  {
    name: "Lavender Dusk",
    id: "lavender-dusk",
    navBg: "bg-purple-950",
    navText: "text-white",
    navHover: "hover:text-purple-300",
    heroGradient: "from-purple-950 via-purple-900 to-violet-950",
    accent: "bg-purple-500",
    accentLight: "bg-purple-100 text-purple-800",
    accentDark: "bg-purple-700",
    sectionAlt: "bg-purple-50",
    cardBg: "bg-white",
    cardBorder: "border-purple-200",
    footerBg: "bg-purple-950",
    footerText: "text-purple-200",
    buttonPrimary: "bg-purple-500 hover:bg-purple-600 text-white",
    buttonHover: "hover:bg-purple-600",
    tag: "bg-purple-500",
    preview: "#a855f7",
  },
  {
    name: "Copper Industrial",
    id: "copper-industrial",
    navBg: "bg-zinc-900",
    navText: "text-amber-200",
    navHover: "hover:text-amber-400",
    heroGradient: "from-zinc-900 via-zinc-800 to-amber-950",
    accent: "bg-amber-600",
    accentLight: "bg-amber-100 text-amber-900",
    accentDark: "bg-amber-800",
    sectionAlt: "bg-zinc-100",
    cardBg: "bg-white",
    cardBorder: "border-amber-300",
    footerBg: "bg-zinc-900",
    footerText: "text-amber-200",
    buttonPrimary: "bg-amber-600 hover:bg-amber-700 text-white",
    buttonHover: "hover:bg-amber-700",
    tag: "bg-amber-600",
    preview: "#d97706",
  },
  {
    name: "Nordic Silver",
    id: "nordic-silver",
    navBg: "bg-gray-800",
    navText: "text-gray-100",
    navHover: "hover:text-teal-400",
    heroGradient: "from-gray-800 via-gray-700 to-teal-900",
    accent: "bg-teal-500",
    accentLight: "bg-teal-100 text-teal-800",
    accentDark: "bg-teal-700",
    sectionAlt: "bg-gray-50",
    cardBg: "bg-white",
    cardBorder: "border-teal-200",
    footerBg: "bg-gray-800",
    footerText: "text-teal-200",
    buttonPrimary: "bg-teal-500 hover:bg-teal-600 text-white",
    buttonHover: "hover:bg-teal-600",
    tag: "bg-teal-500",
    preview: "#14b8a6",
  },
];

export const designThemes = [
  { id: "modern", name: "Modern Clean", description: "Clean lines, generous whitespace" },
  { id: "bold", name: "Bold Impact", description: "Large typography, strong contrasts" },
  { id: "elegant", name: "Elegant Refined", description: "Subtle curves, refined details" },
];
